### ISSUE TITLE
Exclude pfelement from elements in build

### ISSUE THREAD

**Issue by kylebuch8** [kylebuch8/patternfly-elements-lit#1]
Currently the build is trying to mark anything that begins with a path of `..` as external, but I don't think it working. When I look in the dist directories of `pfe-card` and `pfe-badge`, it shows this at the top of the files.

```
// ../pfelement/dist/pfelement.js
var t = window.ShadowRoot && (window.ShadyCSS === void 0 || window.ShadyCSS.nativeShadow) && "adoptedStyleSheets" in Document.prototype && "replace" in CSSStyleSheet.prototype;
var e = Symbol();
...
```

**Comment by mwcz** [comment]
Note to self: https://esbuild.github.io/api/#outbase

I love esbuild.

**Comment by kylebuch8** [comment]
This has been fixed.
